Solves the line truncation issue
build/dependencies/h5fortran/src/write.f90:95:132:

   95 |     if(any(iend - istart > ddims)) error stop 'ERROR:h5fortran:create: iend - istart > dset_dims'  // dname // ' in ' // self%filename
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
build/dependencies/h5fortran/src/write.f90:95:132:

   95 |     if(any(iend - istart > ddims)) error stop 'ERROR:h5fortran:create: iend - istart > dset_dims'  // dname // ' in ' // self%filename
      |                                                                                                                                    1

Error: ‘filena’ at (1) is not a member of the ‘hdf5_file’ structure; did you mean ‘filename’?
compilation terminated due to -fmax-errors=1.
f951: some warnings being treated as errors
<ERROR> Compilation failed for object " build_dependencies_h5fortran_src_write.f90.o "
<ERROR> stopping due to failed compilation
STOP 1